mkdir -p /workspace/ABComparative/results/5.AllGroups/hv/faas/
cp /workspace/ABComparative/results/2.Annotation/hv_INF079/hv_INF079.faa /workspace/ABComparative/results/5.AllGroups/hv/faas/
cp /workspace/ABComparative/results/2.Annotation/hv_INF119/hv_INF119.faa /workspace/ABComparative/results/5.AllGroups/hv/faas/
cp /workspace/ABComparative/results/2.Annotation/hv_INF125/hv_INF125.faa /workspace/ABComparative/results/5.AllGroups/hv/faas/
cp /workspace/ABComparative/results/2.Annotation/hv_INF177/hv_INF177.faa /workspace/ABComparative/results/5.AllGroups/hv/faas/
cp /workspace/ABComparative/results/2.Annotation/hv_INF192/hv_INF192.faa /workspace/ABComparative/results/5.AllGroups/hv/faas/
cp /workspace/ABComparative/results/2.Annotation/hv_INF341/hv_INF341.faa /workspace/ABComparative/results/5.AllGroups/hv/faas/
cp /workspace/ABComparative/results/2.Annotation/hv_INF157/hv_INF157.faa /workspace/ABComparative/results/5.AllGroups/hv/faas/
cp /workspace/ABComparative/results/2.Annotation/hv_INF158/hv_INF158.faa /workspace/ABComparative/results/5.AllGroups/hv/faas/
cp /workspace/ABComparative/results/2.Annotation/hv_INF281/hv_INF281.faa /workspace/ABComparative/results/5.AllGroups/hv/faas/
cp /workspace/ABComparative/results/2.Annotation/hv_INF298/hv_INF298.faa /workspace/ABComparative/results/5.AllGroups/hv/faas/
cp /workspace/ABComparative/results/2.Annotation/hv_INF042/hv_INF042.faa /workspace/ABComparative/results/5.AllGroups/hv/faas/
cp /workspace/ABComparative/results/2.Annotation/hv_INF059/hv_INF059.faa /workspace/ABComparative/results/5.AllGroups/hv/faas/
cp /workspace/ABComparative/results/2.Annotation/hv_INF163/hv_INF163.faa /workspace/ABComparative/results/5.AllGroups/hv/faas/
cp /workspace/ABComparative/results/2.Annotation/hv_INF164/hv_INF164.faa /workspace/ABComparative/results/5.AllGroups/hv/faas/
cp /workspace/ABComparative/results/2.Annotation/hv_INF174/hv_INF174.faa /workspace/ABComparative/results/5.AllGroups/hv/faas/
cp /workspace/ABComparative/results/2.Annotation/hv_INF201/hv_INF201.faa /workspace/ABComparative/results/5.AllGroups/hv/faas/
cp /workspace/ABComparative/results/2.Annotation/hv_INF274/hv_INF274.faa /workspace/ABComparative/results/5.AllGroups/hv/faas/
cp /workspace/ABComparative/results/2.Annotation/hv_INF278/hv_INF278.faa /workspace/ABComparative/results/5.AllGroups/hv/faas/
cp /workspace/ABComparative/results/2.Annotation/hv_INF299/hv_INF299.faa /workspace/ABComparative/results/5.AllGroups/hv/faas/
cp /workspace/ABComparative/results/2.Annotation/hv_INF358/hv_INF358.faa /workspace/ABComparative/results/5.AllGroups/hv/faas/
mkdir -p /workspace/ABComparative/results/5.AllGroups/lv/faas/
cp /workspace/ABComparative/results/2.Annotation/lv_INF032/lv_INF032.faa /workspace/ABComparative/results/5.AllGroups/lv/faas/
cp /workspace/ABComparative/results/2.Annotation/lv_INF102/lv_INF102.faa /workspace/ABComparative/results/5.AllGroups/lv/faas/
cp /workspace/ABComparative/results/2.Annotation/lv_INF156/lv_INF156.faa /workspace/ABComparative/results/5.AllGroups/lv/faas/
cp /workspace/ABComparative/results/2.Annotation/lv_INF215/lv_INF215.faa /workspace/ABComparative/results/5.AllGroups/lv/faas/
cp /workspace/ABComparative/results/2.Annotation/lv_INF319/lv_INF319.faa /workspace/ABComparative/results/5.AllGroups/lv/faas/
cp /workspace/ABComparative/results/2.Annotation/lv_INF277/lv_INF277.faa /workspace/ABComparative/results/5.AllGroups/lv/faas/
cp /workspace/ABComparative/results/2.Annotation/lv_INF302/lv_INF302.faa /workspace/ABComparative/results/5.AllGroups/lv/faas/
cp /workspace/ABComparative/results/2.Annotation/lv_INF346/lv_INF346.faa /workspace/ABComparative/results/5.AllGroups/lv/faas/
cp /workspace/ABComparative/results/2.Annotation/lv_INF044/lv_INF044.faa /workspace/ABComparative/results/5.AllGroups/lv/faas/
cp /workspace/ABComparative/results/2.Annotation/lv_INF049/lv_INF049.faa /workspace/ABComparative/results/5.AllGroups/lv/faas/
cp /workspace/ABComparative/results/2.Annotation/lv_INF188/lv_INF188.faa /workspace/ABComparative/results/5.AllGroups/lv/faas/
cp /workspace/ABComparative/results/2.Annotation/lv_INF223/lv_INF223.faa /workspace/ABComparative/results/5.AllGroups/lv/faas/
cp /workspace/ABComparative/results/2.Annotation/lv_INF247/lv_INF247.faa /workspace/ABComparative/results/5.AllGroups/lv/faas/
cp /workspace/ABComparative/results/2.Annotation/lv_INF249/lv_INF249.faa /workspace/ABComparative/results/5.AllGroups/lv/faas/
cp /workspace/ABComparative/results/2.Annotation/lv_INF250/lv_INF250.faa /workspace/ABComparative/results/5.AllGroups/lv/faas/
cp /workspace/ABComparative/results/2.Annotation/lv_INF322/lv_INF322.faa /workspace/ABComparative/results/5.AllGroups/lv/faas/
cp /workspace/ABComparative/results/2.Annotation/lv_INF329/lv_INF329.faa /workspace/ABComparative/results/5.AllGroups/lv/faas/
cp /workspace/ABComparative/results/2.Annotation/lv_INF344/lv_INF344.faa /workspace/ABComparative/results/5.AllGroups/lv/faas/
cp /workspace/ABComparative/results/2.Annotation/lv_INF355/lv_INF355.faa /workspace/ABComparative/results/5.AllGroups/lv/faas/
cp /workspace/ABComparative/results/2.Annotation/lv_INF357/lv_INF357.faa /workspace/ABComparative/results/5.AllGroups/lv/faas/
cp /workspace/ABComparative/results/2.Annotation/lv_INF361/lv_INF361.faa /workspace/ABComparative/results/5.AllGroups/lv/faas/
cp /workspace/ABComparative/results/2.Annotation/lv_INF321/lv_INF321.faa /workspace/ABComparative/results/5.AllGroups/lv/faas/
