mkdir -p /home/nathanyoung54/ABComp/ABComparative/results/4.RoaryGroup/
mkdir -p /home/nathanyoung54/ABComp/ABComparative/results/4.RoaryGroup/hvCRAB/
cp /home/nathanyoung54/ABComp/ABComparative/results/2.Annotation/hvCRAB_A0006/hvCRAB_A0006.gff /home/nathanyoung54/ABComp/ABComparative/results/4.RoaryGroup/hvCRAB/
cp /home/nathanyoung54/ABComp/ABComparative/results/2.Annotation/hvCRAB_A0197/hvCRAB_A0197.gff /home/nathanyoung54/ABComp/ABComparative/results/4.RoaryGroup/hvCRAB/
cp /home/nathanyoung54/ABComp/ABComparative/results/2.Annotation/hvCRAB_A0220/hvCRAB_A0220.gff /home/nathanyoung54/ABComp/ABComparative/results/4.RoaryGroup/hvCRAB/
mkdir -p /home/nathanyoung54/ABComp/ABComparative/results/4.RoaryGroup/hvCRAB-MDR/
cp /home/nathanyoung54/ABComp/ABComparative/results/2.Annotation/hvCRAB-MDR_A0062/hvCRAB-MDR_A0062.gff /home/nathanyoung54/ABComp/ABComparative/results/4.RoaryGroup/hvCRAB-MDR/
cp /home/nathanyoung54/ABComp/ABComparative/results/2.Annotation/hvCRAB-MDR_A0277/hvCRAB-MDR_A0277.gff /home/nathanyoung54/ABComp/ABComparative/results/4.RoaryGroup/hvCRAB-MDR/
cp /home/nathanyoung54/ABComp/ABComparative/results/2.Annotation/hvCRAB-MDR_A0292/hvCRAB-MDR_A0292.gff /home/nathanyoung54/ABComp/ABComparative/results/4.RoaryGroup/hvCRAB-MDR/
mkdir -p /home/nathanyoung54/ABComp/ABComparative/results/4.RoaryGroup/lvCRAB/
cp /home/nathanyoung54/ABComp/ABComparative/results/2.Annotation/lvCRAB_A0274/lvCRAB_A0274.gff /home/nathanyoung54/ABComp/ABComparative/results/4.RoaryGroup/lvCRAB/
cp /home/nathanyoung54/ABComp/ABComparative/results/2.Annotation/lvCRAB_A0291/lvCRAB_A0291.gff /home/nathanyoung54/ABComp/ABComparative/results/4.RoaryGroup/lvCRAB/
mkdir -p /home/nathanyoung54/ABComp/ABComparative/results/4.RoaryGroup/lv/
cp /home/nathanyoung54/ABComp/ABComparative/results/2.Annotation/lv_A0075/lv_A0075.gff /home/nathanyoung54/ABComp/ABComparative/results/4.RoaryGroup/lv/
cp /home/nathanyoung54/ABComp/ABComparative/results/2.Annotation/lv_A0137/lv_A0137.gff /home/nathanyoung54/ABComp/ABComparative/results/4.RoaryGroup/lv/
