mkdir -p /home/nathanyoung54/ABComp/ABComparative/results/5.AllGroups/hvCRAB/faas/
cp /home/nathanyoung54/ABComp/ABComparative/results/2.Annotation/hvCRAB_A0006/hvCRAB_A0006.faa /home/nathanyoung54/ABComp/ABComparative/results/5.AllGroups/hvCRAB/faas/
cp /home/nathanyoung54/ABComp/ABComparative/results/2.Annotation/hvCRAB_A0197/hvCRAB_A0197.faa /home/nathanyoung54/ABComp/ABComparative/results/5.AllGroups/hvCRAB/faas/
cp /home/nathanyoung54/ABComp/ABComparative/results/2.Annotation/hvCRAB_A0220/hvCRAB_A0220.faa /home/nathanyoung54/ABComp/ABComparative/results/5.AllGroups/hvCRAB/faas/
mkdir -p /home/nathanyoung54/ABComp/ABComparative/results/5.AllGroups/hvCRAB-MDR/faas/
cp /home/nathanyoung54/ABComp/ABComparative/results/2.Annotation/hvCRAB-MDR_A0062/hvCRAB-MDR_A0062.faa /home/nathanyoung54/ABComp/ABComparative/results/5.AllGroups/hvCRAB-MDR/faas/
cp /home/nathanyoung54/ABComp/ABComparative/results/2.Annotation/hvCRAB-MDR_A0277/hvCRAB-MDR_A0277.faa /home/nathanyoung54/ABComp/ABComparative/results/5.AllGroups/hvCRAB-MDR/faas/
cp /home/nathanyoung54/ABComp/ABComparative/results/2.Annotation/hvCRAB-MDR_A0292/hvCRAB-MDR_A0292.faa /home/nathanyoung54/ABComp/ABComparative/results/5.AllGroups/hvCRAB-MDR/faas/
mkdir -p /home/nathanyoung54/ABComp/ABComparative/results/5.AllGroups/lvCRAB/faas/
cp /home/nathanyoung54/ABComp/ABComparative/results/2.Annotation/lvCRAB_A0274/lvCRAB_A0274.faa /home/nathanyoung54/ABComp/ABComparative/results/5.AllGroups/lvCRAB/faas/
cp /home/nathanyoung54/ABComp/ABComparative/results/2.Annotation/lvCRAB_A0291/lvCRAB_A0291.faa /home/nathanyoung54/ABComp/ABComparative/results/5.AllGroups/lvCRAB/faas/
mkdir -p /home/nathanyoung54/ABComp/ABComparative/results/5.AllGroups/lv/faas/
cp /home/nathanyoung54/ABComp/ABComparative/results/2.Annotation/lv_A0075/lv_A0075.faa /home/nathanyoung54/ABComp/ABComparative/results/5.AllGroups/lv/faas/
cp /home/nathanyoung54/ABComp/ABComparative/results/2.Annotation/lv_A0137/lv_A0137.faa /home/nathanyoung54/ABComp/ABComparative/results/5.AllGroups/lv/faas/
