mkdir /workspace/ABComparative/results/4.RoaryGroup/
mkdir /workspace/ABComparative/results/4.RoaryGroup/hv/
cp /workspace/ABComparative/results/2.Annotation/hv_INF079/hv_INF079.gff /workspace/ABComparative/results/4.RoaryGroup/hv/
cp /workspace/ABComparative/results/2.Annotation/hv_INF119/hv_INF119.gff /workspace/ABComparative/results/4.RoaryGroup/hv/
cp /workspace/ABComparative/results/2.Annotation/hv_INF125/hv_INF125.gff /workspace/ABComparative/results/4.RoaryGroup/hv/
cp /workspace/ABComparative/results/2.Annotation/hv_INF177/hv_INF177.gff /workspace/ABComparative/results/4.RoaryGroup/hv/
cp /workspace/ABComparative/results/2.Annotation/hv_INF192/hv_INF192.gff /workspace/ABComparative/results/4.RoaryGroup/hv/
cp /workspace/ABComparative/results/2.Annotation/hv_INF341/hv_INF341.gff /workspace/ABComparative/results/4.RoaryGroup/hv/
cp /workspace/ABComparative/results/2.Annotation/hv_INF157/hv_INF157.gff /workspace/ABComparative/results/4.RoaryGroup/hv/
cp /workspace/ABComparative/results/2.Annotation/hv_INF158/hv_INF158.gff /workspace/ABComparative/results/4.RoaryGroup/hv/
cp /workspace/ABComparative/results/2.Annotation/hv_INF281/hv_INF281.gff /workspace/ABComparative/results/4.RoaryGroup/hv/
cp /workspace/ABComparative/results/2.Annotation/hv_INF298/hv_INF298.gff /workspace/ABComparative/results/4.RoaryGroup/hv/
cp /workspace/ABComparative/results/2.Annotation/hv_INF042/hv_INF042.gff /workspace/ABComparative/results/4.RoaryGroup/hv/
cp /workspace/ABComparative/results/2.Annotation/hv_INF059/hv_INF059.gff /workspace/ABComparative/results/4.RoaryGroup/hv/
cp /workspace/ABComparative/results/2.Annotation/hv_INF163/hv_INF163.gff /workspace/ABComparative/results/4.RoaryGroup/hv/
cp /workspace/ABComparative/results/2.Annotation/hv_INF164/hv_INF164.gff /workspace/ABComparative/results/4.RoaryGroup/hv/
cp /workspace/ABComparative/results/2.Annotation/hv_INF174/hv_INF174.gff /workspace/ABComparative/results/4.RoaryGroup/hv/
cp /workspace/ABComparative/results/2.Annotation/hv_INF201/hv_INF201.gff /workspace/ABComparative/results/4.RoaryGroup/hv/
cp /workspace/ABComparative/results/2.Annotation/hv_INF274/hv_INF274.gff /workspace/ABComparative/results/4.RoaryGroup/hv/
cp /workspace/ABComparative/results/2.Annotation/hv_INF278/hv_INF278.gff /workspace/ABComparative/results/4.RoaryGroup/hv/
cp /workspace/ABComparative/results/2.Annotation/hv_INF299/hv_INF299.gff /workspace/ABComparative/results/4.RoaryGroup/hv/
cp /workspace/ABComparative/results/2.Annotation/hv_INF358/hv_INF358.gff /workspace/ABComparative/results/4.RoaryGroup/hv/
mkdir /workspace/ABComparative/results/4.RoaryGroup/lv/
cp /workspace/ABComparative/results/2.Annotation/lv_INF032/lv_INF032.gff /workspace/ABComparative/results/4.RoaryGroup/lv/
cp /workspace/ABComparative/results/2.Annotation/lv_INF102/lv_INF102.gff /workspace/ABComparative/results/4.RoaryGroup/lv/
cp /workspace/ABComparative/results/2.Annotation/lv_INF156/lv_INF156.gff /workspace/ABComparative/results/4.RoaryGroup/lv/
cp /workspace/ABComparative/results/2.Annotation/lv_INF215/lv_INF215.gff /workspace/ABComparative/results/4.RoaryGroup/lv/
cp /workspace/ABComparative/results/2.Annotation/lv_INF319/lv_INF319.gff /workspace/ABComparative/results/4.RoaryGroup/lv/
cp /workspace/ABComparative/results/2.Annotation/lv_INF277/lv_INF277.gff /workspace/ABComparative/results/4.RoaryGroup/lv/
cp /workspace/ABComparative/results/2.Annotation/lv_INF302/lv_INF302.gff /workspace/ABComparative/results/4.RoaryGroup/lv/
cp /workspace/ABComparative/results/2.Annotation/lv_INF346/lv_INF346.gff /workspace/ABComparative/results/4.RoaryGroup/lv/
cp /workspace/ABComparative/results/2.Annotation/lv_INF044/lv_INF044.gff /workspace/ABComparative/results/4.RoaryGroup/lv/
cp /workspace/ABComparative/results/2.Annotation/lv_INF049/lv_INF049.gff /workspace/ABComparative/results/4.RoaryGroup/lv/
cp /workspace/ABComparative/results/2.Annotation/lv_INF188/lv_INF188.gff /workspace/ABComparative/results/4.RoaryGroup/lv/
cp /workspace/ABComparative/results/2.Annotation/lv_INF223/lv_INF223.gff /workspace/ABComparative/results/4.RoaryGroup/lv/
cp /workspace/ABComparative/results/2.Annotation/lv_INF247/lv_INF247.gff /workspace/ABComparative/results/4.RoaryGroup/lv/
cp /workspace/ABComparative/results/2.Annotation/lv_INF249/lv_INF249.gff /workspace/ABComparative/results/4.RoaryGroup/lv/
cp /workspace/ABComparative/results/2.Annotation/lv_INF250/lv_INF250.gff /workspace/ABComparative/results/4.RoaryGroup/lv/
cp /workspace/ABComparative/results/2.Annotation/lv_INF322/lv_INF322.gff /workspace/ABComparative/results/4.RoaryGroup/lv/
cp /workspace/ABComparative/results/2.Annotation/lv_INF329/lv_INF329.gff /workspace/ABComparative/results/4.RoaryGroup/lv/
cp /workspace/ABComparative/results/2.Annotation/lv_INF344/lv_INF344.gff /workspace/ABComparative/results/4.RoaryGroup/lv/
cp /workspace/ABComparative/results/2.Annotation/lv_INF355/lv_INF355.gff /workspace/ABComparative/results/4.RoaryGroup/lv/
cp /workspace/ABComparative/results/2.Annotation/lv_INF357/lv_INF357.gff /workspace/ABComparative/results/4.RoaryGroup/lv/
cp /workspace/ABComparative/results/2.Annotation/lv_INF361/lv_INF361.gff /workspace/ABComparative/results/4.RoaryGroup/lv/
cp /workspace/ABComparative/results/2.Annotation/lv_INF321/lv_INF321.gff /workspace/ABComparative/results/4.RoaryGroup/lv/
