# This is a default configuration setting for the overall Snakemake run
# Please adjust the parameters or names accordingly

# Workspace directory
workspace: "/workspace/ABComparative/results/"

# Flye
# flye_read_type: "--pacbio-hifi"
# flye_genome_size: "4m"
# flye_threads: 16

# Trimmomatic
trimmomatic_threads: 8
trimmomatic_phred: "-phred33"
trimmomatic_adapter: "adapters/TruSeq3-PE.fa"
trimmomatic_seed_mismatch: 2
trimmomatic_palindrome_clip_thres: 30
trimmomatic_simple_clip_thres: 10
trimmomatic_leading: 3
trimmomatic_trailing: 3
trimmomatic_sliding1: 4
trimmomatic_sliding2: 15
trimmomatic_minlen: 36

# Polypolish
polypolish_threads: 8

# Busco
busco_lineage: "bacteria_odb10"

# Quast
quast_threads: 4 

# Prokka
prokka_ref_threads: 8
prokka_ref_kingdom: "Bacteria"

prokka_strain_threads: 8
prokka_strain_kingdom: "Bacteria"

# Roary
roary_pairwise_threads: 8
roary_pairwise_pident: 90

roary_within_group_threads: 16
roary_within_group_pident: 90

# Move GFF files
move_gff_script: "move_gffs.sh"
group_info: "groups_original.yml"

# Move FAA files
move_faa_script: "move_faas.sh"

# Egg-NOG-mapper
emapper_core_pident: 30
emapper_core_evalue: 0.001
emapper_core_score: 60
emapper_core_query_cover: 70
emapper_core_subject_cover: 70
emapper_core_cpu: 8 

emapper_shells_pident: 30
emapper_shells_evalue: 0.001
emapper_shells_score: 60
emapper_shells_query_cover: 70
emapper_shells_subject_cover: 70
emapper_shells_cpu: 8 

# COG visualization
types_core: "Core"
types_shells: "Shell"

# ABRicate
abricate_minid: 50
abricate_mincov: 80
