Convergent:
  - ARLG-3346
  - ARLG-4365
  - ARLG-4803
  - CRE-015
  - DHQP1701672
  - K014
  - KPN1402
  - KPN1409
  - KPN226
  - KPN415
  - KPN482
  - OC1092
hvKP:
  - hvKP1
  - hvKP2
  - hvKP4
  - hvKP5
  - KPN13
  - KPN49
  - KPN63
  - KPN8
  - KPPR1
  - NTUH-K2044
  - TK421
MDR-cKP:
  - CRE-017
  - CRE-041
  - CRE-118
  - CRE-163
  - CRE-204
  - CRE-229
  - CRE-231
  - CRE-234
  - CRE-243
  - CRE-265
  - OC1116
NON-MDR-cKP:
  - 1155-IKP-00
  - KPN23
  - KPN62
  - KPN68
  - KPN80
  - TK77